"""empty message

Revision ID: ac0227a89b4c
Revises: 
Create Date: 2019-08-01 03:51:34.894594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac0227a89b4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('from_number', sa.Text(), nullable=False),
    sa.Column('to_number', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
